Repository CodersCamp2021-HK/CodersCamp2021.Project.JavaScript, pull requests merged in 2021-12, with the labels that each got.

#32 Issue 31 dodać css variables z figmy oraz dołączyć import fontu
  src/public/style.css
Labels: priority: high

#41 Issue 22 komponent reguły #22
  src/components/RulesTextBox/RulesTextBox.js
  src/components/RulesTextBox/RulesTextBox.module.css
  src/components/RulesTextBox/RulesTextBox.test.js
  src/components/RulesTextBox/index.js
  src/components/index.js
Labels: 🦄 for design review

#35 add functions for creating game types list and distinguish selected types
  src/components/GameTypeButton/GameTypeButton.js
  src/components/GameTypeButton/GameTypeButton.module.css
  src/components/GameTypeButton/index.js
  src/components/GameTypes/GameTypes.js
  src/components/GameTypes/GameTypes.module.css
  src/components/GameTypes/index.js
  src/components/index.js
  src/public/style.css
Labels: priority: high

#48 feat(components): add nextQuestion Button, join all buttons component into one named Button
  src/components/Button/Button.js
  src/components/Button/Button.module.css
  src/components/Button/Button.test.js
  src/components/GameTypeButton/GameTypeButton.js
  src/components/GameTypeButton/GameTypeButton.module.css
  src/components/GameTypeButton/index.js
  src/components/GameTypes/GameTypes.js
  src/components/MenuButton/MenuButton.js
  src/components/MenuButton/MenuButton.module.css
  src/components/MenuButton/MenuButton.test.js
  src/components/MenuButton/index.js
  src/components/index.js
  src/pages/Home/Home.js
Labels: type: ♻️ refactor

#61 Issue 50 layout quiz
  src/components/BackgroundDecoration/BackgroundDecoration.js
  src/components/BackgroundDecoration/BackgroundDecoration.module.css
  src/components/BackgroundDecoration/index.js
  src/components/Button/Button.module.css
  src/components/GameTypes/GameTypes.module.css
  src/components/index.js
  src/pages/Quiz/Quiz.js
  src/pages/Quiz/Quiz.module.css
  src/pages/Quiz/Quiz.test.js
  src/public/img/ellipse.svg
  src/public/style.css
Labels: priority: medium 🟡

#66 fix path for images and fix width of buttons
  src/components/BackgroundDecoration/BackgroundDecoration.js
  src/components/Button/Button.module.css
  src/components/Logo/Logo.js
  src/pages/Quiz/Quiz.js
Labels: priority: critical 🔴

#78 Issue 52 komponent input dodanie nazwy gracza
  src/components/Input/Input.js
  src/components/Input/Input.module.css
  src/components/Input/index.js
  src/components/index.js
Labels: priority: high 🟠

#81 Poprawa wyglądu różnych stanów przycisku wyboru kategorii #80
  src/components/Button/Button.module.css
  src/components/GameTypes/GameTypes.module.css
Labels: ⏱ 1 minute PR

#82 Issue 70 tabela widok rankingu
  src/components/RankingTable/RankingTable.js
  src/components/RankingTable/RankingTable.module.css
  src/components/RankingTable/RankingTable.test.js
  src/components/RankingTable/index.js
  src/components/index.js
  src/shared/ranking.js
  src/shared/ranking.test.js
Labels: type: ✨ feat

#91 add favicon in rick and morty style
  index.html
  src/public/favicon.ico
  src/public/favicon.svg
Labels: priority: low ⚪️

#74 Komponent Timer - create layout and basic feature
  src/components/Timer/Timer.js
  src/components/Timer/Timer.module.css
  src/components/Timer/index.js
  src/components/index.js
  src/pages/Quiz/Quiz.js
  src/public/style.css
  yarn.lock
Labels: priority: critical 🔴

#92 Issue 71 layout widok rankingu
  src/components/RankingTable/RankingTable.module.css
  src/pages/Home/Home.js
  src/pages/Ranking/Ranking.js
  src/pages/Ranking/Ranking.module.css
  src/pages/Ranking/index.js
  src/pages/index.js
Labels: type: ✨ feat

#97 Issue 73 usprawnienia boxów na stronie głównej
  src/components/RulesTextBox/RulesTextBox.js
Labels: priority: high 🟠, type: 🐛 fix

#95 add possibility to clear timer interval on game end
  src/components/Timer/Timer.js
  src/pages/Quiz/Quiz.js
Labels: priority: medium 🟡, type: 🐛 fix
